services:
  backend:
    build: ./server
    container_name: bank_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - EXTERNAL_API_URL=https://jsonplaceholder.typicode.com/users
      - JWT_SECRET=super_secret_jwt_key_2026

  frontend:
    build: ./client
    container_name: bank_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
